env:
  node: true
  es2021: true
  browser: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-var:
    - error
  no-console:
    - error
  eqeqeq:
    - error
  curly:
    - error
    - all
